[cosmic-ray]
module-path = "find_meetings"
python-version = ""
timeout = 60.0
excluded-modules = []
test-command = "python -m pytest"

[cosmic-ray.execution-engine]
name = "local"

[cosmic-ray.cloning]
method = "copy"
commands = [
  "pip3 install pytest"
]
